# to run: docker-compose run
#
# Create a .env file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
#
#
version: "2"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - WEBUI_PORT=8080
    volumes:
      - ${MOUNT_POINT}/qbittorrent:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${MOUNT_POINT}/radarr:/config
      - ${DOWNLOADS}:/data
      - ${MEDIA_PATH}/movies:/movies
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${MOUNT_POINT}/sonarr:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${DOWNLOADS}:/data
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
    ports:
      - "9117:9117"
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${MOUNT_POINT}/sabnzbd:/config
      - ${DOWNLOADS}:/data  #optional
      #- ${DOWNLOADS}/imcomplete:/incomplete-downloads #optional
    ports:
      - 8081:8080
    restart: unless-stopped
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${MOUNT_POINT}/nzbhydra:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${MOUNT_POINT}/bazarr/config:/config
      - ${MEDIA_PATH}/movies:/movies #optional
      - ${MEDIA_PATH}/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped 
